# Generated by Django 5.2.4 on 2025-08-03 11:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='recording',
            field=models.FileField(blank=True, help_text='Call recording file (for call activities only)', null=True, upload_to='Call Recordings/'),
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note content')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(limit_choices_to={'activity_type': 'task'}, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.activity')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
