# Generated by Django 5.2.4 on 2025-08-03 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_activity_recording_tasknote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sofa', 'Sofa'), ('bed', 'Bed'), ('recliner', 'Recliner'), ('sofa_cum_bed', 'Sofa Cum Bed')], max_length=50, unique=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Product categories this lead is interested in', related_name='leads', to='leads.category'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Product description', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Product price', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the product is currently available')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='leads.category')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LeadProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this product')),
                ('notes', models.TextField(blank=True, help_text='Notes about this product for this lead', null=True)),
                ('price_quoted', models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted to customer', max_digits=10, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_products', to='leads.lead')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_products', to='leads.product')),
            ],
            options={
                'ordering': ['product__category', 'product__name'],
                'unique_together': {('lead', 'product')},
            },
        ),
    ]
