# Generated by Django 5.1.7 on 2025-08-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_category_lead_categories_product_leadproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='products_data',
            field=models.JSONField(blank=True, default=dict, help_text='Products data stored as JSON'),
        ),
    ]
