# Generated by Django 5.1.7 on 2025-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_products_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='interested_product_url',
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_stage',
            field=models.CharField(choices=[('cold_follow_up', 'Cold Follow Up'), ('warm_follow_up', 'Warm Follow Up'), ('factory_visit', 'Factory Visit'), ('production', 'Production'), ('delivered', 'Delivered'), ('not_fit', 'Not Fit')], default='cold_follow_up', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('customer', 'Customer')], default='active', max_length=20),
        ),
    ]
